name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: croservices/cro-http:0.8.5

    steps:
    - uses: actions/checkout@v2

    - name: Raku version
      run: raku -v

    - name: Update zef
      run:  zef install --force-install Test::META

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Run tests
      run: zef test -v --debug .
